SELECT DISTINCT a.*
	,CASE 
		WHEN a.QTD_SEPARADA > 0
			THEN TEMPO_GASTO / a.QTD_SEPARADA
		ELSE 0
		END media_tempo
FROM (
	SELECT 
		ONF.NF AS MAPA
		,S.OPERADOR_SEPARACAO CD_OPERADOR
		,OPER.CD_EMPRESA CD_EMPRESA_OPERADOR
		,E.NOME_COMPLETO NOME_OPERADOR
		,CASE 
			WHEN S.SITUACAO_SEPARACAO = 'I'
				THEN 'Iniciado'
			ELSE 'Finalizado'
			END SITUACAO
		,S.DATA_INICIO_SEPARACAO DATA_INICIO
		,substrING(S.HORA_INICIO_SEPARACAO, 1, 2) + ':' + substrING(S.HORA_INICIO_SEPARACAO, 3, 2) HORA_INICIO
		,S.DATA_FIM_SEPARACAO DATA_TERMINO
		,CASE 
			WHEN S.HORA_FIM_SEPARACAO IS NOT NULL
				THEN substrING(S.HORA_FIM_SEPARACAO, 1, 2) + ':' + substrING(S.HORA_FIM_SEPARACAO, 3, 2)
			ELSE ' '
			END HORA_TERMINO
		,(
			SELECT SUM(QUANTIDADE_ORIGINAL)
			FROM TESEPEXPEDICAOITEM WITH (NOLOCK)
			WHERE ID_SEPARACAO = S.ID_SEPARACAO
			) QTD_ORIGINAL
		,(
			SELECT COUNT(*)
			FROM TESEPEXPEDICAOITEM WITH (NOLOCK)
			WHERE ID_SEPARACAO = S.ID_SEPARACAO
			) QTD_SKUs -- QUANTIDADE DE SKUs
		,(
			SELECT SUM(QUANTIDADE_SEPARADA)
			FROM TESEPEXPEDICAOITEM WITH (NOLOCK)
			WHERE ID_SEPARACAO = S.ID_SEPARACAO
			) QTD_SEPARADA
		,CASE 
			WHEN S.SITUACAO_SEPARACAO = 'F'
				THEN DBO.EXFC_CALC_DIF_HORAS((S.Data_Inicio_Separacao + (SUBSTRING(S.HORA_INICIO_SEPARACAO, 1, 2) + ':' + SUBSTRING(S.HORA_INICIO_SEPARACAO, 3, 2) + ':' + SUBSTRING(S.HORA_INICIO_SEPARACAO, 5, 2))), (S.Data_Fim_Separacao + (SUBSTRING(S.HORA_FIM_SEPARACAO, 1, 2) + ':' + SUBSTRING(S.HORA_FIM_SEPARACAO, 3, 2) + ':' + SUBSTRING(S.HORA_FIM_SEPARACAO, 5, 2))))
			ELSE 0
			END TEMPO_GASTO
	FROM TESEPEXPEDICAO S WITH (NOLOCK)
	INNER JOIN TEOPERADORXEMP OPER WITH (NOLOCK) ON OPER.CD_OPERADOR = S.OPERADOR_SEPARACAO
	INNER JOIN GEEMPRES E WITH (NOLOCK) ON E.CD_EMPRESA = OPER.CD_EMPRESA
	INNER JOIN TEHORACRIACAONF ONF WITH (NOLOCK) ON ONF.EMPRESA  = E.CD_EMPRESA
	WHERE S.DATA_INICIO_SEPARACAO BETWEEN '2025-04-01'
			AND '2025-04-10'
		AND S.SITUACAO_SEPARACAO BETWEEN ' '
			AND 'Z'
		AND S.OPERADOR_SEPARACAO BETWEEN '13'
			AND '13'
	) a